@extends('layouts.admin')
@section('content')
    @livewire('counter')
    @livewire('counter')
    @livewire('counter')
    @livewire('counter')
    @livewire('counter')
    @livewire('counter')
@endsection
